name: ai_schedule_planner
description: AI-powered schedule planning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # AI & API
  google_generative_ai: ^0.4.0
  http: ^1.1.2

  # Calendar
  table_calendar: ^3.0.9

  # Date/Time
  intl: ^0.18.1

  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.0
  shared_preferences: ^2.2.2

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Chat History
  uuid: ^3.0.7

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true